package com.amaze.filemanager.database.daos;

import static com.amaze.filemanager.database.ExplorerDatabase.COLUMN_CLOUD_SERVICE;
import static com.amaze.filemanager.database.ExplorerDatabase.TABLE_CLOUD_PERSIST;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Transaction;
import androidx.room.Update;

import com.amaze.filemanager.database.models.explorer.CloudEntry;

import java.util.List;

import io.reactivex.Completable;
import io.reactivex.Single;

/**
 * {@link Dao} interface definition for {@link CloudEntry}. Concrete class is generated by Room
 * during build.
 *
 * @see Dao
 * @see CloudEntry
 * @see com.amaze.filemanager.database.ExplorerDatabase
 */
@Dao
public interface CloudEntryDao {

    @Insert
    Completable insert(CloudEntry entry);

    @Query(
            "SELECT * FROM " + TABLE_CLOUD_PERSIST + " WHERE " + COLUMN_CLOUD_SERVICE + " = :serviceType")
    Single<CloudEntry> findByServiceType(int serviceType);

    @Query("SELECT * FROM " + TABLE_CLOUD_PERSIST)
    Single<List<CloudEntry>> list();

    @Update
    Completable update(CloudEntry entry);

    @Delete
    Completable delete(CloudEntry entry);

    @Transaction
    @Query("DELETE FROM " + TABLE_CLOUD_PERSIST)
    Completable clear();
}
