package com.amaze.filemanager.database.daos;

import static com.amaze.filemanager.database.UtilitiesDatabase.COLUMN_PATH;
import static com.amaze.filemanager.database.UtilitiesDatabase.TABLE_GRID;

import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.amaze.filemanager.database.models.utilities.Grid;

import java.util.List;

import io.reactivex.Completable;
import io.reactivex.Single;

/**
 * {@link Dao} interface definition for {@link Grid}. Concrete class is generated by Room during
 * build.
 *
 * @see Dao
 * @see Grid
 * @see com.amaze.filemanager.database.UtilitiesDatabase
 */
@Dao
public interface GridEntryDao {

    @Insert
    Completable insert(Grid instance);

    @Update
    Completable update(Grid instance);

    @Query("SELECT " + COLUMN_PATH + " FROM " + TABLE_GRID)
    Single<List<String>> listPaths();

    @Query("DELETE FROM " + TABLE_GRID + " WHERE " + COLUMN_PATH + " = :path")
    Completable deleteByPath(String path);
}
