package com.amaze.filemanager.database.daos;

import static com.amaze.filemanager.database.ExplorerDatabase.COLUMN_PATH;
import static com.amaze.filemanager.database.ExplorerDatabase.TABLE_SORT;

import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Transaction;
import androidx.room.Update;

import com.amaze.filemanager.database.models.explorer.Sort;

import io.reactivex.Completable;
import io.reactivex.Single;

/**
 * {@link Dao} interface definition for {@link Sort}. Concrete class is generated by Room during
 * build.
 *
 * @see Dao
 * @see Sort
 * @see com.amaze.filemanager.database.ExplorerDatabase
 */
@Dao
public interface SortDao {

    @Insert
    Completable insert(Sort entity);

    @Query("SELECT * FROM " + TABLE_SORT + " WHERE " + COLUMN_PATH + " = :path")
    Single<Sort> find(String path);

    @Transaction
    @Query("DELETE FROM " + TABLE_SORT + " WHERE " + COLUMN_PATH + " = :path")
    Completable clear(String path);

    @Update
    Completable update(Sort entity);
}
